
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.15.5"
    steps:
      - checkout
      - run:
          name: Back-End Install
          command: |
            npm install
      - run:
          name: Back-End Build
          command: |
            npm run build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - "./*"

  deploy:
    docker:
      - image: "cimg/node:14.15.5"
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Deploy BE App
          command: |
            npm run deploy

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master